name: Tests

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.25", "1.26"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: go test -race -cover -coverprofile="coverage.out" ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: coverage.out
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Run linter
        uses: golangci/golangci-lint-action@v9.0.0
        with:
          args: --timeout 5m

      - name: Security audit
        run: |
          go run golang.org/x/vuln/cmd/govulncheck@latest ./...
